/**
 * truckData.ts
 *
 * Comprehensive US truck/van/semi data for the driver signup form.
 * Covers all major makes sold in the US with their truck/van/semi model lines.
 */

// ---- Truck Makes ----
export const TRUCK_MAKES = [
  "Ford",
  "Chevrolet",
  "GMC",
  "RAM",
  "Toyota",
  "Nissan",
  "Honda",
  "Jeep",
  "Rivian",
  "Freightliner",
  "Kenworth",
  "Peterbilt",
  "International",
  "Volvo",
  "Mack",
  "Western Star",
  "Mercedes-Benz",
  "Sprinter",
  "Ford Transit",
  "Ram ProMaster",
  "Chevrolet Express",
  "GMC Savana",
  "Isuzu",
  "Hino",
  "Mitsubishi Fuso",
  "UD Trucks",
  "Other",
] as const;

// ---- Models by Make ----
export const TRUCK_MODELS_BY_MAKE: Record<string, string[]> = {
  Ford: [
    "F-150",
    "F-250 Super Duty",
    "F-350 Super Duty",
    "F-450 Super Duty",
    "F-550 Super Duty",
    "F-600 Super Duty",
    "Ranger",
    "Maverick",
    "Transit Cargo Van",
    "Transit Connect",
    "Transit 150",
    "Transit 250",
    "Transit 350",
    "Transit 350 HD",
    "E-Series Cargo Van",
    "F-650",
    "F-750",
  ],
  Chevrolet: [
    "Silverado 1500",
    "Silverado 2500 HD",
    "Silverado 3500 HD",
    "Silverado 4500 HD",
    "Silverado 5500 HD",
    "Silverado 6500 HD",
    "Colorado",
    "S-10",
    "Express 1500 Cargo",
    "Express 2500 Cargo",
    "Express 3500 Cargo",
    "Low Cab Forward",
  ],
  GMC: [
    "Sierra 1500",
    "Sierra 2500 HD",
    "Sierra 3500 HD",
    "Canyon",
    "Savana 1500 Cargo",
    "Savana 2500 Cargo",
    "Savana 3500 Cargo",
    "TopKick",
  ],
  RAM: [
    "1500",
    "1500 Classic",
    "2500",
    "3500",
    "3500 Chassis Cab",
    "4500 Chassis Cab",
    "5500 Chassis Cab",
    "ProMaster 1500 Cargo",
    "ProMaster 2500 Cargo",
    "ProMaster 3500 Cargo",
    "ProMaster City",
    "Dakota",
  ],
  Toyota: [
    "Tacoma",
    "Tundra",
    "Hilux",
  ],
  Nissan: [
    "Frontier",
    "Titan",
    "Titan XD",
    "NV Cargo 1500",
    "NV Cargo 2500",
    "NV Cargo 3500",
    "NV200 Compact Cargo",
  ],
  Honda: ["Ridgeline"],
  Jeep: ["Gladiator"],
  Rivian: ["R1T"],
  Freightliner: [
    "Cascadia",
    "Columbia",
    "Classic",
    "FLD",
    "M2 106",
    "M2 112",
    "Sprinter Cargo Van",
    "Sprinter Crew Van",
    "Business Class M2",
    "114SD",
    "122SD",
  ],
  Kenworth: [
    "T680",
    "T880",
    "W900",
    "T270",
    "T370",
    "T470",
    "T660",
    "T800",
    "C500",
  ],
  Peterbilt: [
    "389",
    "579",
    "567",
    "348",
    "337",
    "330",
    "220",
    "536",
    "520",
  ],
  International: [
    "LT Series",
    "RH Series",
    "HX Series",
    "MV Series",
    "CV Series",
    "Durastar",
    "Workstar",
    "Transtar",
  ],
  Volvo: [
    "VNL 300",
    "VNL 400",
    "VNL 600",
    "VNL 740",
    "VNL 760",
    "VNL 860",
    "VHD",
    "VAH",
    "VNR",
  ],
  Mack: [
    "Anthem",
    "Pinnacle",
    "Granite",
    "TerraPro",
    "LR",
    "MD Series",
  ],
  "Western Star": [
    "4700",
    "4800",
    "4900",
    "5700XE",
    "6900",
    "47X",
    "49X",
    "57X",
  ],
  "Mercedes-Benz": [
    "Sprinter 1500 Cargo",
    "Sprinter 2500 Cargo",
    "Sprinter 3500 Cargo",
    "Sprinter 3500 XD",
    "Metris Cargo",
  ],
  Sprinter: [
    "1500 Cargo Van",
    "2500 Cargo Van",
    "3500 Cargo Van",
    "3500 XD Cargo Van",
  ],
  "Ford Transit": [
    "150 Cargo Van",
    "250 Cargo Van",
    "350 Cargo Van",
    "350 HD Cargo Van",
  ],
  "Ram ProMaster": [
    "1500 Cargo Van",
    "2500 Cargo Van",
    "3500 Cargo Van",
  ],
  "Chevrolet Express": [
    "1500 Cargo Van",
    "2500 Cargo Van",
    "3500 Cargo Van",
  ],
  "GMC Savana": [
    "1500 Cargo Van",
    "2500 Cargo Van",
    "3500 Cargo Van",
  ],
  Isuzu: [
    "NPR",
    "NPR-HD",
    "NQR",
    "NRR",
    "FTR",
    "FVR",
    "FXR",
    "FVZ",
  ],
  Hino: [
    "155",
    "195",
    "195h",
    "258",
    "268",
    "338",
    "XL7",
    "XL8",
  ],
  "Mitsubishi Fuso": [
    "FE130",
    "FE160",
    "FE180",
    "FG140",
    "FK200",
    "FM330",
  ],
  "UD Trucks": [
    "Condor",
    "Quon",
  ],
  Other: ["Other"],
};

// ---- Vehicle Types ----
export const TRUCK_TYPES = [
  { value: "pickup", label: "Pickup Truck" },
  { value: "box_truck", label: "Box Truck" },
  { value: "flatbed", label: "Flatbed" },
  { value: "cargo_van", label: "Cargo Van" },
  { value: "passenger_van", label: "Passenger Van" },
  { value: "semi_truck", label: "Semi Truck / 18-Wheeler" },
  { value: "dump_truck", label: "Dump Truck" },
  { value: "other", label: "Other" },
] as const;

// ---- Model Years (1990 → current year + 1) ----
const currentYear = new Date().getFullYear();
export const TRUCK_YEARS: number[] = Array.from(
  { length: currentYear - 1989 + 1 },
  (_, i) => currentYear + 1 - i
);

// ---- Service Area Cities ----
// All cities from the FeaturedDudes metro data + expanded list
export const SERVICE_AREA_CITIES = [
  // Atlanta Metro
  "Atlanta, GA",
  "East Point, GA",
  "College Park, GA",
  "Decatur, GA",
  "Douglasville, GA",
  "Austell, GA",
  "Lithia Springs, GA",
  "Smyrna, GA",
  "Marietta, GA",
  "Sandy Springs, GA",
  "Duluth, GA",
  "Norcross, GA",
  "Lawrenceville, GA",
  "Tucker, GA",
  "Stone Mountain, GA",
  "Alpharetta, GA",
  "Roswell, GA",
  "Kennesaw, GA",
  "Peachtree City, GA",
  "Fayetteville, GA",
  // Houston Metro
  "Houston, TX",
  "Katy, TX",
  "Sugar Land, TX",
  "Pearland, TX",
  "Cypress, TX",
  "Spring, TX",
  "Humble, TX",
  "Pasadena, TX",
  "Missouri City, TX",
  "The Woodlands, TX",
  "Baytown, TX",
  "League City, TX",
  "Friendswood, TX",
  "Conroe, TX",
  "Kingwood, TX",
  // Dallas / Fort Worth
  "Dallas, TX",
  "Fort Worth, TX",
  "Arlington, TX",
  "Plano, TX",
  "Garland, TX",
  "Irving, TX",
  "Frisco, TX",
  "McKinney, TX",
  "Grand Prairie, TX",
  "Mesquite, TX",
  "Carrollton, TX",
  "Denton, TX",
  "Lewisville, TX",
  "Allen, TX",
  "Richardson, TX",
  // Austin Metro
  "Austin, TX",
  "Round Rock, TX",
  "Cedar Park, TX",
  "Georgetown, TX",
  "Pflugerville, TX",
  "Kyle, TX",
  "Buda, TX",
  "San Marcos, TX",
  "Leander, TX",
  // San Antonio
  "San Antonio, TX",
  "New Braunfels, TX",
  "Schertz, TX",
  "Converse, TX",
  "Universal City, TX",
  // Other Major US Cities
  "Los Angeles, CA",
  "San Diego, CA",
  "San Jose, CA",
  "San Francisco, CA",
  "Fresno, CA",
  "Sacramento, CA",
  "Long Beach, CA",
  "Oakland, CA",
  "Bakersfield, CA",
  "Anaheim, CA",
  "Phoenix, AZ",
  "Tucson, AZ",
  "Mesa, AZ",
  "Chandler, AZ",
  "Scottsdale, AZ",
  "Glendale, AZ",
  "Tempe, AZ",
  "Chicago, IL",
  "Aurora, IL",
  "Naperville, IL",
  "Joliet, IL",
  "Rockford, IL",
  "New York, NY",
  "Brooklyn, NY",
  "Queens, NY",
  "Bronx, NY",
  "Buffalo, NY",
  "Yonkers, NY",
  "Philadelphia, PA",
  "Pittsburgh, PA",
  "Allentown, PA",
  "Miami, FL",
  "Jacksonville, FL",
  "Tampa, FL",
  "Orlando, FL",
  "St. Petersburg, FL",
  "Hialeah, FL",
  "Tallahassee, FL",
  "Fort Lauderdale, FL",
  "Charlotte, NC",
  "Raleigh, NC",
  "Greensboro, NC",
  "Durham, NC",
  "Winston-Salem, NC",
  "Columbus, OH",
  "Cleveland, OH",
  "Cincinnati, OH",
  "Toledo, OH",
  "Akron, OH",
  "Detroit, MI",
  "Grand Rapids, MI",
  "Warren, MI",
  "Sterling Heights, MI",
  "Lansing, MI",
  "Nashville, TN",
  "Memphis, TN",
  "Knoxville, TN",
  "Chattanooga, TN",
  "Clarksville, TN",
  "Denver, CO",
  "Colorado Springs, CO",
  "Aurora, CO",
  "Fort Collins, CO",
  "Lakewood, CO",
  "Seattle, WA",
  "Spokane, WA",
  "Tacoma, WA",
  "Vancouver, WA",
  "Bellevue, WA",
  "Portland, OR",
  "Eugene, OR",
  "Salem, OR",
  "Gresham, OR",
  "Las Vegas, NV",
  "Henderson, NV",
  "Reno, NV",
  "North Las Vegas, NV",
  "Minneapolis, MN",
  "St. Paul, MN",
  "Rochester, MN",
  "Duluth, MN",
  "Kansas City, MO",
  "St. Louis, MO",
  "Springfield, MO",
  "Independence, MO",
  "Indianapolis, IN",
  "Fort Wayne, IN",
  "Evansville, IN",
  "South Bend, IN",
  "Louisville, KY",
  "Lexington, KY",
  "Bowling Green, KY",
  "Baltimore, MD",
  "Frederick, MD",
  "Gaithersburg, MD",
  "Rockville, MD",
  "Washington, DC",
  "Virginia Beach, VA",
  "Norfolk, VA",
  "Chesapeake, VA",
  "Richmond, VA",
  "Arlington, VA",
  "Boston, MA",
  "Worcester, MA",
  "Springfield, MA",
  "Cambridge, MA",
  "Albuquerque, NM",
  "Santa Fe, NM",
  "Las Cruces, NM",
  "Omaha, NE",
  "Lincoln, NE",
  "Bellevue, NE",
  "Milwaukee, WI",
  "Madison, WI",
  "Green Bay, WI",
  "Other",
].sort((a, b) => {
  // Keep "Other" at the bottom
  if (a === "Other") return 1;
  if (b === "Other") return -1;
  return a.localeCompare(b);
});

// ---- Clever driver taglines ----
export const DRIVER_TAGLINE_EXAMPLES = [
  "Just A Man With A Truck",
  "Your Stuff, My Truck, No Problem",
  "Built Ford Tough, Priced Right",
  "I Haul, You Chill",
  "No Job Too Heavy",
  "From Point A to Point B, Stress-Free",
  "The Dude Who Gets It Done",
  "Reliable, Careful, On Time",
  "Hauling With Heart",
  "Your Neighborhood Mover",
];
